name: Run Snyk Scan for Package Vulnerabilities for semver-release-action
'on': push
jobs:
  snyk-scan-go:
    permissions:
      contents: read
      id-token: write
    uses: epidemicsound/github-workflows/.github/workflows/snyk-scan-go.yaml@main
